# Generated by Django 5.1.4 on 2025-01-15 14:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesstype',
            name='category_list',
            field=models.ManyToManyField(default=1, related_name='business_types', to='stock.category'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='business_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='account.businesstype'),
        ),
        migrations.AddField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='businesstype',
            index=models.Index(fields=['name'], name='business_type_name_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['username'], name='username_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['shop_name'], name='shop_name_idx'),
        ),
    ]
