# Generated by Django 5.1.4 on 2025-01-29 13:48

from django.db import migrations, models

from account import scripts


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='sin tipo', max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('category_list', models.ManyToManyField(related_name='business_types', to='stock.category')),
            ],
            options={
                'indexes': [models.Index(fields=['name'], name='business_type_name_idx')],
            },
        ),
        migrations.RunPython(scripts.create_default_data)
    ]
