# Generated by Django 5.1.4 on 2025-01-03 14:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='business_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pages.businesstype'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(default='0', max_length=30),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='shop_name',
            field=models.CharField(default='sin nombre', max_length=100),
        ),
    ]
