# Generated by Django 5.1.4 on 2025-02-06 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spends', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spend',
            name='category',
            field=models.CharField(choices=[('alquiler', 'Alquiler'), ('electricidad', 'Electricidad'), ('agua', 'Agua'), ('internet', 'Internet'), ('las', 'Gas'), ('teléfono', 'Teléfono'), ('insumos y materias primas', 'Insumos y Materias Primas'), ('sueldos', 'Sueldos'), ('bonificaciones', 'Bonificaciones'), ('seguridad social', 'Seguridad Social'), ('combustible', 'Combustible'), ('mantenimiento', 'Mantenimiento'), ('reparaciones', 'Reparaciones'), ('impuestos', 'Impuestos'), ('seguros', 'Seguros'), ('prestamos y financiamientos', 'Préstamos y Financiamientos'), ('gastos inesperados', 'Gastos Inesperados'), ('inversión en infraestructura', 'Inversión en Infraestructura')], max_length=100),
        ),
        migrations.DeleteModel(
            name='SpendCategory',
        ),
    ]
