# Generated by Django 5.1.4 on 2025-01-10 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='sin tipo', max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('category_list', models.ManyToManyField(default=1, related_name='business_types', to='stock.category')),
            ],
            options={
                'indexes': [models.Index(fields=['name'], name='business_type_name_idx')],
            },
        ),
    ]
