# Generated by Django 5.1.4 on 2025-01-03 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stock', '0002_product_user_alter_category_name_alter_product_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='sin tipo', max_length=100)),
                ('description', models.TextField(null=True, blank=True)),
                ('category_list', models.ManyToManyField(default=1, related_name='business_types', to='stock.category')),
            ],
        ),
    ]
