# Generated by Django 5.1.4 on 2025-01-06 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_product_user_alter_category_name_alter_product_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='uom',
            field=models.CharField(choices=[('unidad', 'Unidad'), ('kilogramo', 'Kilogramo'), ('miligramo', 'Miligramo'), ('mililitros', 'Mililitros')], default='unidad', max_length=30),
        ),
    ]
